version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    timezone: Europe/Berlin
  open-pull-requests-limit: 10
  assignees:
  - mreinsch
  ignore:
  - dependency-name: rubocop
    versions:
    - 1.10.0
    - 1.11.0
    - 1.12.0
    - 1.9.0
    - 1.9.1
  - dependency-name: bundler
    versions:
    - 2.2.10
    - 2.2.11
    - 2.2.12
    - 2.2.13
    - 2.2.14
    - 2.2.15
    - 2.2.7
    - 2.2.8
    - 2.2.9
  - dependency-name: webmock
    versions:
    - 3.12.1
  - dependency-name: activesupport
    versions:
    - 6.1.1
    - 6.1.2
    - 6.1.2.1
    - 6.1.3
  - dependency-name: thor
    versions:
    - 1.1.0
  - dependency-name: rake
    versions:
    - 13.0.3
  - dependency-name: rspec
    versions:
    - 3.10.0
